### ISSUE TITLE
Mnemonic problem

### ISSUE THREAD

**Issue by Luphia** [BOLT-Protocol/TideWallet#101]
版本： v18(1.0.1)
1. 助記詞： cry hub inmate cliff sun program public else atom absurd release inherit funny edge assault
2. 密碼： 12345678
3. 助記詞回復失敗

**Comment by paulhuang1102** [comment]
Using https://bip32jp.github.io/english/ check the result.
Public Key (Hex) was same as PaperWallet.getExtendedPublicKey() publicKey on line 128, but Derived Public Key was different from bitcoinKey on line 132.

**Comment by Luphia** [comment]
釋出版本：v20(1.0.2)
