### ISSUE TITLE
Wallet recovery by Mnemonic can not make transaction

### ISSUE THREAD

**Issue by Luphia** [BOLT-Protocol/TideWallet#102]
版本： v18(1.0.1)
1. 以註記詞回復錢包
2. 助記詞： cry hub inmate cliff sun program public else atom absurd release inherit funny edge assault
3. 密碼： 12345
4. 送出 0.1 TTN 至 0xD885833741F554A0e64fFd1141887d65e0dded01
5. 簽名私鑰與實際錢包不同

**Comment by paulhuang1102** [comment]
1. 助記詞產生 keystore 時的私鑰，直接用 bip39 seed (64bytes)
2. PaperWallet magicSeed 的 input 如果長度 < 64 bytes(一般 Ethereum privateKey 為 32 bytes)，才執行 keccak256 * 2

**Comment by Luphia** [comment]
釋出版本：v19(1.0.2)
