### ISSUE TITLE
Confirm button does not work after transaction failed

### ISSUE THREAD

**Issue by Luphia** [BOLT-Protocol/TideWallet#104]
版本： v18(1.0.1)
1. 使用 #102 流程
2. 交易失敗後再次點擊 confirm
3. 完成驗證後無任何反應

**Comment by paulhuang1102** [comment]
此問題為 LocalAuthBloc 只能驗證一次
驗完之後 state 都會是 isAuthenicated，blocListener 沒監聽到 state 改變，
看看要不要清除 LocalAuthBloc isAuthenicated state

**Comment by Luphia** [comment]
API 呼叫並取得回應後清除 LocalAuthBloc isAuthenicated state

**Comment by Luphia** [comment]
釋出版本：v20(1.0.2)
