### ISSUE TITLE
How to add ERC 20 token in tidewallet

### ISSUE THREAD

**Issue by Chariotz** [BOLT-Protocol/TideWallet#62]
版本： TideWallet 3 0.1.1（6）
1. 點擊 添加幣種 
2. 進入頁面「support ERC20 TOKEN」頁面，下面有「請輸入地址」。

問題： 
1 這個請輸入地址是否多餘？
2. 或者是否可以採用Tidewallet 2 中的自選幣種添加，用戶可以先添加選項，然後再轉帳？

**Comment by Luphia** [comment]
版本： v18(1.0.1)
1. 暫時移除手動添加 ERC20 幣種功能
2. 用戶收到 ERC20 Token 即會自動新增
3. 若需支援用戶手動添加，需提供預設 ERC20 支援清單
