### ISSUE TITLE
no response after copy the receiving address successfully

### ISSUE THREAD

**Issue by Chariotz** [BOLT-Protocol/TideWallet#63]
版本： TideWallet 3 0.1.1（6）

在轉入ETH 頁面中，
點擊「複製錢包地址」後，沒有任何反應，用戶容易誤以為沒有複製成功。
希望在複製成功後，可以反饋一個文本框，提示，「已經複製成功，可以去轉出錢包粘貼地址啦」之類提示。

**Comment by Luphia** [comment]
釋出版本：v20(1.0.2)
